// <auto-generated />
using System;
using MedicalReports.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicalReports.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedicalReports.Core.Entities.Guideline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MatchingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCategory")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Category", "SubCategory")
                        .IsUnique()
                        .HasFilter("[SubCategory] IS NOT NULL");

                    b.ToTable("Guidelines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Cholesterol",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MatchingType = "Numeric",
                            SubCategory = "Total"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Cholesterol",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MatchingType = "Numeric",
                            SubCategory = "Hdl"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Cholesterol",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MatchingType = "Numeric",
                            SubCategory = "Ldl"
                        },
                        new
                        {
                            Id = 4,
                            Category = "BloodSugar",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MatchingType = "Numeric"
                        },
                        new
                        {
                            Id = 5,
                            Category = "BloodPressure",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MatchingType = "Numeric",
                            SubCategory = "Systolic"
                        },
                        new
                        {
                            Id = 6,
                            Category = "BloodPressure",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MatchingType = "Numeric",
                            SubCategory = "Diastolic"
                        },
                        new
                        {
                            Id = 7,
                            Category = "ExerciseWeeklyMinutes",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MatchingType = "Numeric"
                        },
                        new
                        {
                            Id = 8,
                            Category = "SleepQuality",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MatchingType = "Textual"
                        },
                        new
                        {
                            Id = 9,
                            Category = "StressLevels",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MatchingType = "Textual"
                        },
                        new
                        {
                            Id = 10,
                            Category = "DietQuality",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MatchingType = "Textual"
                        });
                });

            modelBuilder.Entity("MedicalReports.Core.Entities.GuidelineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuidelineId")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaxValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextualValue")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GuidelineId");

                    b.ToTable("GuidelineItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuidelineId = 1,
                            MaxValue = 199m,
                            Status = "Optimal"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuidelineId = 1,
                            MaxValue = 239m,
                            MinValue = 200m,
                            Status = "NeedsAttention"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuidelineId = 1,
                            MinValue = 240m,
                            Status = "SeriousIssue"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuidelineId = 2,
                            MinValue = 61m,
                            Status = "Optimal"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuidelineId = 2,
                            MaxValue = 60m,
                            MinValue = 40m,
                            Status = "NeedsAttention"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuidelineId = 2,
                            MaxValue = 39m,
                            Status = "SeriousIssue"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuidelineId = 3,
                            MaxValue = 99m,
                            Status = "Optimal"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuidelineId = 3,
                            MaxValue = 129m,
                            MinValue = 100m,
                            Status = "NeedsAttention"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuidelineId = 3,
                            MinValue = 130m,
                            Status = "SeriousIssue"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuidelineId = 4,
                            MaxValue = 99m,
                            MinValue = 70m,
                            Status = "Optimal"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuidelineId = 4,
                            MaxValue = 125m,
                            MinValue = 100m,
                            Status = "NeedsAttention"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuidelineId = 4,
                            MinValue = 126m,
                            Status = "SeriousIssue"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuidelineId = 5,
                            MaxValue = 119m,
                            Status = "Optimal"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuidelineId = 5,
                            MaxValue = 129m,
                            MinValue = 120m,
                            Status = "NeedsAttention"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuidelineId = 5,
                            MinValue = 130m,
                            Status = "SeriousIssue"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuidelineId = 6,
                            MaxValue = 79m,
                            Status = "Optimal"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuidelineId = 6,
                            MinValue = 80m,
                            Status = "SeriousIssue"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuidelineId = 7,
                            MinValue = 150m,
                            Status = "Optimal"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuidelineId = 7,
                            MaxValue = 149m,
                            MinValue = 75m,
                            Status = "NeedsAttention"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuidelineId = 7,
                            MaxValue = 74m,
                            Status = "SeriousIssue"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuidelineId = 8,
                            Status = "Optimal",
                            TextualValue = "7-9 hours with restful sleep"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuidelineId = 8,
                            Status = "NeedsAttention",
                            TextualValue = "5-6 hours or frequent disturbances"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuidelineId = 8,
                            Status = "SeriousIssue",
                            TextualValue = "<5 hours or severe sleep issues"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuidelineId = 9,
                            Status = "Optimal",
                            TextualValue = "Low self-reported stress"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuidelineId = 9,
                            Status = "NeedsAttention",
                            TextualValue = "Moderate self-reported stress"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuidelineId = 9,
                            Status = "SeriousIssue",
                            TextualValue = "High chronic stress affecting well-being"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuidelineId = 10,
                            Status = "Optimal",
                            TextualValue = "Balanced, nutrient-rich diet"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuidelineId = 10,
                            Status = "NeedsAttention",
                            TextualValue = "Processed or high-sugar diet"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GuidelineId = 10,
                            Status = "SeriousIssue",
                            TextualValue = "Poor nutrition with deficiencies"
                        });
                });

            modelBuilder.Entity("MedicalReports.Core.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1980, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@test.com",
                            Gender = "Male",
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1992, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.smith@test.com",
                            Gender = "Female",
                            Name = "Jane Smith"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1973, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emily.johnson@test.com",
                            Gender = "Female",
                            Name = "Emily Johnson"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1997, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "michael.brown@test.com",
                            Gender = "Male",
                            Name = "Michael Brown"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1986, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sophia.davis@test.com",
                            Gender = "Female",
                            Name = "Sophia Davis"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1965, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "james.wilson@test.com",
                            Gender = "Male",
                            Name = "James Wilson"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1995, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "laura.martinez@test.com",
                            Gender = "Female",
                            Name = "Laura Martinez"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1981, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "daniel.lee@test.com",
                            Gender = "Male",
                            Name = "Daniel Lee"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1989, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "olivia.white@test.com",
                            Gender = "Female",
                            Name = "Olivia White"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1974, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "william.carter@test.com",
                            Gender = "Male",
                            Name = "William Carter"
                        });
                });

            modelBuilder.Entity("MedicalReports.Core.Entities.PatientBloodWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MeasurementDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("SubCategory")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientsBloodWork");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Cholesterol",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 1,
                            SubCategory = "Total",
                            Unit = "",
                            Value = 210m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Cholesterol",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 1,
                            SubCategory = "HDL",
                            Unit = "",
                            Value = 50m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Cholesterol",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 1,
                            SubCategory = "LDL",
                            Unit = "",
                            Value = 130m
                        },
                        new
                        {
                            Id = 4,
                            Category = "BloodSugar",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 1,
                            Unit = "",
                            Value = 95m
                        },
                        new
                        {
                            Id = 5,
                            Category = "BloodPressure",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 1,
                            SubCategory = "Systolic",
                            Unit = "",
                            Value = 130m
                        },
                        new
                        {
                            Id = 6,
                            Category = "BloodPressure",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 1,
                            SubCategory = "Diastolic",
                            Unit = "",
                            Value = 85m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Cholesterol",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 2,
                            SubCategory = "Total",
                            Unit = "",
                            Value = 180m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Cholesterol",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 2,
                            SubCategory = "HDL",
                            Unit = "",
                            Value = 60m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Cholesterol",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 2,
                            SubCategory = "LDL",
                            Unit = "",
                            Value = 100m
                        },
                        new
                        {
                            Id = 10,
                            Category = "BloodSugar",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 2,
                            Unit = "",
                            Value = 85m
                        },
                        new
                        {
                            Id = 11,
                            Category = "BloodPressure",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 2,
                            SubCategory = "Systolic",
                            Unit = "",
                            Value = 120m
                        },
                        new
                        {
                            Id = 12,
                            Category = "BloodPressure",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 2,
                            SubCategory = "Diastolic",
                            Unit = "",
                            Value = 80m
                        },
                        new
                        {
                            Id = 13,
                            Category = "Cholesterol",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 3,
                            SubCategory = "Total",
                            Unit = "",
                            Value = 250m
                        },
                        new
                        {
                            Id = 14,
                            Category = "Cholesterol",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 3,
                            SubCategory = "HDL",
                            Unit = "",
                            Value = 35m
                        },
                        new
                        {
                            Id = 15,
                            Category = "Cholesterol",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 3,
                            SubCategory = "LDL",
                            Unit = "",
                            Value = 150m
                        },
                        new
                        {
                            Id = 16,
                            Category = "BloodSugar",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 3,
                            Unit = "",
                            Value = 110m
                        },
                        new
                        {
                            Id = 17,
                            Category = "BloodPressure",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 3,
                            SubCategory = "Systolic",
                            Unit = "",
                            Value = 140m
                        },
                        new
                        {
                            Id = 18,
                            Category = "BloodPressure",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 3,
                            SubCategory = "Diastolic",
                            Unit = "",
                            Value = 90m
                        },
                        new
                        {
                            Id = 19,
                            Category = "Cholesterol",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 4,
                            SubCategory = "HDL",
                            Unit = "",
                            Value = 55m
                        },
                        new
                        {
                            Id = 20,
                            Category = "Cholesterol",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 4,
                            SubCategory = "LDL",
                            Unit = "",
                            Value = 120m
                        },
                        new
                        {
                            Id = 21,
                            Category = "BloodSugar",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 4,
                            Unit = "",
                            Value = 90m
                        },
                        new
                        {
                            Id = 22,
                            Category = "BloodPressure",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 4,
                            SubCategory = "Systolic",
                            Unit = "",
                            Value = 118m
                        },
                        new
                        {
                            Id = 23,
                            Category = "BloodPressure",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 4,
                            SubCategory = "Diastolic",
                            Unit = "",
                            Value = 78m
                        },
                        new
                        {
                            Id = 24,
                            Category = "Cholesterol",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 5,
                            SubCategory = "Total",
                            Unit = "",
                            Value = 220m
                        },
                        new
                        {
                            Id = 25,
                            Category = "Cholesterol",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 5,
                            SubCategory = "HDL",
                            Unit = "",
                            Value = 45m
                        },
                        new
                        {
                            Id = 26,
                            Category = "Cholesterol",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 5,
                            SubCategory = "LDL",
                            Unit = "",
                            Value = 135m
                        },
                        new
                        {
                            Id = 27,
                            Category = "BloodSugar",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 5,
                            Unit = "",
                            Value = 100m
                        },
                        new
                        {
                            Id = 28,
                            Category = "BloodPressure",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 5,
                            SubCategory = "Systolic",
                            Unit = "",
                            Value = 128m
                        },
                        new
                        {
                            Id = 29,
                            Category = "BloodPressure",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 5,
                            SubCategory = "Diastolic",
                            Unit = "",
                            Value = 83m
                        },
                        new
                        {
                            Id = 30,
                            Category = "Cholesterol",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 6,
                            SubCategory = "Total",
                            Unit = "",
                            Value = 260m
                        },
                        new
                        {
                            Id = 31,
                            Category = "Cholesterol",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 6,
                            SubCategory = "HDL",
                            Unit = "",
                            Value = 40m
                        },
                        new
                        {
                            Id = 32,
                            Category = "Cholesterol",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 6,
                            SubCategory = "LDL",
                            Unit = "",
                            Value = 155m
                        },
                        new
                        {
                            Id = 33,
                            Category = "BloodSugar",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 6,
                            Unit = "",
                            Value = 130m
                        },
                        new
                        {
                            Id = 34,
                            Category = "BloodPressure",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 6,
                            SubCategory = "Systolic",
                            Unit = "",
                            Value = 145m
                        },
                        new
                        {
                            Id = 35,
                            Category = "BloodPressure",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 6,
                            SubCategory = "Diastolic",
                            Unit = "",
                            Value = 95m
                        },
                        new
                        {
                            Id = 36,
                            Category = "Cholesterol",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 7,
                            SubCategory = "Total",
                            Unit = "",
                            Value = 185m
                        },
                        new
                        {
                            Id = 37,
                            Category = "Cholesterol",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 7,
                            SubCategory = "HDL",
                            Unit = "",
                            Value = 58m
                        },
                        new
                        {
                            Id = 38,
                            Category = "Cholesterol",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 7,
                            SubCategory = "LDL",
                            Unit = "",
                            Value = 110m
                        },
                        new
                        {
                            Id = 39,
                            Category = "BloodSugar",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 7,
                            Unit = "",
                            Value = 92m
                        },
                        new
                        {
                            Id = 40,
                            Category = "BloodPressure",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 7,
                            SubCategory = "Systolic",
                            Unit = "",
                            Value = 122m
                        },
                        new
                        {
                            Id = 41,
                            Category = "BloodPressure",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 7,
                            SubCategory = "Diastolic",
                            Unit = "",
                            Value = 79m
                        },
                        new
                        {
                            Id = 42,
                            Category = "Cholesterol",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 8,
                            SubCategory = "Total",
                            Unit = "",
                            Value = 230m
                        },
                        new
                        {
                            Id = 43,
                            Category = "Cholesterol",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 8,
                            SubCategory = "HDL",
                            Unit = "",
                            Value = 48m
                        },
                        new
                        {
                            Id = 44,
                            Category = "Cholesterol",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 8,
                            SubCategory = "LDL",
                            Unit = "",
                            Value = 140m
                        },
                        new
                        {
                            Id = 45,
                            Category = "BloodSugar",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 8,
                            Unit = "",
                            Value = 115m
                        },
                        new
                        {
                            Id = 46,
                            Category = "BloodPressure",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 8,
                            SubCategory = "Systolic",
                            Unit = "",
                            Value = 135m
                        },
                        new
                        {
                            Id = 47,
                            Category = "BloodPressure",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 8,
                            SubCategory = "Diastolic",
                            Unit = "",
                            Value = 87m
                        },
                        new
                        {
                            Id = 48,
                            Category = "Cholesterol",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 9,
                            SubCategory = "Total",
                            Unit = "",
                            Value = 195m
                        },
                        new
                        {
                            Id = 49,
                            Category = "Cholesterol",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 9,
                            SubCategory = "HDL",
                            Unit = "",
                            Value = 52m
                        },
                        new
                        {
                            Id = 50,
                            Category = "Cholesterol",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 9,
                            SubCategory = "LDL",
                            Unit = "",
                            Value = 115m
                        },
                        new
                        {
                            Id = 51,
                            Category = "BloodSugar",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 9,
                            Unit = "",
                            Value = 89m
                        },
                        new
                        {
                            Id = 52,
                            Category = "BloodPressure",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 9,
                            SubCategory = "Systolic",
                            Unit = "",
                            Value = 124m
                        },
                        new
                        {
                            Id = 53,
                            Category = "BloodPressure",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 9,
                            SubCategory = "Diastolic",
                            Unit = "",
                            Value = 81m
                        },
                        new
                        {
                            Id = 54,
                            Category = "Cholesterol",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 10,
                            SubCategory = "Total",
                            Unit = "",
                            Value = 240m
                        },
                        new
                        {
                            Id = 55,
                            Category = "Cholesterol",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 10,
                            SubCategory = "HDL",
                            Unit = "",
                            Value = 42m
                        },
                        new
                        {
                            Id = 56,
                            Category = "Cholesterol",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 10,
                            SubCategory = "LDL",
                            Unit = "",
                            Value = 145m
                        },
                        new
                        {
                            Id = 57,
                            Category = "BloodSugar",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 10,
                            Unit = "",
                            Value = 125m
                        },
                        new
                        {
                            Id = 58,
                            Category = "BloodPressure",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 10,
                            SubCategory = "Systolic",
                            Unit = "",
                            Value = 138m
                        },
                        new
                        {
                            Id = 59,
                            Category = "BloodPressure",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MeasurementDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 10,
                            SubCategory = "Diastolic",
                            Unit = "",
                            Value = 89m
                        });
                });

            modelBuilder.Entity("MedicalReports.Core.Entities.PatientQuestionnaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NumericValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponseValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SubCategory")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientsQuestionnaire");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "ExerciseWeeklyMinutes",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumericValue = 90m,
                            PatientId = 1,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "90"
                        },
                        new
                        {
                            Id = 2,
                            Category = "SleepQuality",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 1,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "6 hours, frequent disturbances"
                        },
                        new
                        {
                            Id = 3,
                            Category = "StressLevels",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 1,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "Moderate self-reported stress"
                        },
                        new
                        {
                            Id = 4,
                            Category = "DietQuality",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 1,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "Processed or high-sugar diet"
                        },
                        new
                        {
                            Id = 5,
                            Category = "ExerciseWeeklyMinutes",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumericValue = 160m,
                            PatientId = 2,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "160"
                        },
                        new
                        {
                            Id = 6,
                            Category = "SleepQuality",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 2,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "7 hours, restful sleep"
                        },
                        new
                        {
                            Id = 7,
                            Category = "StressLevels",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 2,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "Low self-reported stress"
                        },
                        new
                        {
                            Id = 8,
                            Category = "DietQuality",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 2,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "Balanced, nutrient-rich diet"
                        },
                        new
                        {
                            Id = 9,
                            Category = "ExerciseWeeklyMinutes",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumericValue = 60m,
                            PatientId = 3,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "60"
                        },
                        new
                        {
                            Id = 10,
                            Category = "SleepQuality",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 3,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "5 hours, frequent disturbances"
                        },
                        new
                        {
                            Id = 11,
                            Category = "StressLevels",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 3,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "High chronic stress affecting well-being"
                        },
                        new
                        {
                            Id = 12,
                            Category = "DietQuality",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 3,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "Poor nutrition with deficiencies"
                        },
                        new
                        {
                            Id = 13,
                            Category = "ExerciseWeeklyMinutes",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumericValue = 200m,
                            PatientId = 4,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "200"
                        },
                        new
                        {
                            Id = 14,
                            Category = "SleepQuality",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 4,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "8 hours, restful sleep"
                        },
                        new
                        {
                            Id = 15,
                            Category = "StressLevels",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 4,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "Low self-reported stress"
                        },
                        new
                        {
                            Id = 16,
                            Category = "DietQuality",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 4,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "Balanced, nutrient-rich diet"
                        },
                        new
                        {
                            Id = 17,
                            Category = "ExerciseWeeklyMinutes",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumericValue = 130m,
                            PatientId = 5,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "130"
                        },
                        new
                        {
                            Id = 18,
                            Category = "SleepQuality",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 5,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "6.5 hours, mild disturbances"
                        },
                        new
                        {
                            Id = 19,
                            Category = "StressLevels",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 5,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "Moderate self-reported stress"
                        },
                        new
                        {
                            Id = 20,
                            Category = "DietQuality",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 5,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "Processed or high-sugar diet"
                        },
                        new
                        {
                            Id = 21,
                            Category = "ExerciseWeeklyMinutes",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumericValue = 40m,
                            PatientId = 6,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "40"
                        },
                        new
                        {
                            Id = 22,
                            Category = "SleepQuality",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 6,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "4.5 hours, severe sleep issues"
                        },
                        new
                        {
                            Id = 23,
                            Category = "StressLevels",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 6,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "High chronic stress affecting well-being"
                        },
                        new
                        {
                            Id = 24,
                            Category = "DietQuality",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 6,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "Poor nutrition with deficiencies"
                        },
                        new
                        {
                            Id = 25,
                            Category = "ExerciseWeeklyMinutes",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumericValue = 170m,
                            PatientId = 7,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "170"
                        },
                        new
                        {
                            Id = 26,
                            Category = "SleepQuality",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 7,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "7.5 hours, restful sleep"
                        },
                        new
                        {
                            Id = 27,
                            Category = "StressLevels",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 7,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "Low self-reported stress"
                        },
                        new
                        {
                            Id = 28,
                            Category = "DietQuality",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 7,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "Balanced, nutrient-rich diet"
                        },
                        new
                        {
                            Id = 29,
                            Category = "ExerciseWeeklyMinutes",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumericValue = 80m,
                            PatientId = 8,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "80"
                        },
                        new
                        {
                            Id = 30,
                            Category = "SleepQuality",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 8,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "6 hours, mild disturbances"
                        },
                        new
                        {
                            Id = 31,
                            Category = "StressLevels",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 8,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "Moderate self-reported stress"
                        },
                        new
                        {
                            Id = 32,
                            Category = "DietQuality",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 8,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "Processed or high-sugar diet"
                        },
                        new
                        {
                            Id = 33,
                            Category = "ExerciseWeeklyMinutes",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumericValue = 150m,
                            PatientId = 9,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "150"
                        },
                        new
                        {
                            Id = 34,
                            Category = "SleepQuality",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 9,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "7 hours, restful sleep"
                        },
                        new
                        {
                            Id = 35,
                            Category = "StressLevels",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 9,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "Low self-reported stress"
                        },
                        new
                        {
                            Id = 36,
                            Category = "DietQuality",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 9,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "Balanced, nutrient-rich diet"
                        },
                        new
                        {
                            Id = 37,
                            Category = "ExerciseWeeklyMinutes",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumericValue = 55m,
                            PatientId = 10,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "55"
                        },
                        new
                        {
                            Id = 38,
                            Category = "SleepQuality",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 10,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "5 hours, frequent disturbances"
                        },
                        new
                        {
                            Id = 39,
                            Category = "StressLevels",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 10,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "High chronic stress affecting well-being"
                        },
                        new
                        {
                            Id = 40,
                            Category = "DietQuality",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PatientId = 10,
                            ResponseDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseValue = "Poor nutrition with deficiencies"
                        });
                });

            modelBuilder.Entity("MedicalReports.Core.Entities.GuidelineItem", b =>
                {
                    b.HasOne("MedicalReports.Core.Entities.Guideline", "Guideline")
                        .WithMany("GuidelineItems")
                        .HasForeignKey("GuidelineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guideline");
                });

            modelBuilder.Entity("MedicalReports.Core.Entities.PatientBloodWork", b =>
                {
                    b.HasOne("MedicalReports.Core.Entities.Patient", "Patient")
                        .WithMany("BloodWork")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MedicalReports.Core.Entities.PatientQuestionnaire", b =>
                {
                    b.HasOne("MedicalReports.Core.Entities.Patient", "Patient")
                        .WithMany("Questionnaires")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MedicalReports.Core.Entities.Guideline", b =>
                {
                    b.Navigation("GuidelineItems");
                });

            modelBuilder.Entity("MedicalReports.Core.Entities.Patient", b =>
                {
                    b.Navigation("BloodWork");

                    b.Navigation("Questionnaires");
                });
#pragma warning restore 612, 618
        }
    }
}
